name: CI

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.platform.name }} ${{ matrix.config.name }}
    runs-on: ${{ matrix.platform.os }}

    strategy:
      fail-fast: false
      matrix:
        platform:
        - { name: Windows VS2022, os: windows-2022 }
        - { name: Linux GCC,      os: ubuntu-latest }
        - { name: Linux Clang,    os: ubuntu-latest, flags: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ }
        - { name: macOS,          os: macos-latest }
        config:
        - { name: Shared, flags: -DBUILD_SHARED_LIBS=TRUE }
        - { name: Static, flags: -DBUILD_SHARED_LIBS=FALSE }

    steps:
    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install libxrandr-dev libxcursor-dev libxi-dev libudev-dev libflac-dev libvorbis-dev libgl1-mesa-dev libegl1-mesa-dev libfreetype-dev

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure
      run: cmake -B build ${{ matrix.platform.flags }} ${{ matrix.config.flags }}

    - name: Build
      run: cmake --build build --config Release

  build-ios:
    name: iOS Unsigned IPA
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        run: brew install cmake

      - name: Configure for iOS
        run: |
          cmake -S . -B build-ios \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_SYSROOT=iphoneos \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_CXX_STANDARD=23 \
            -DBUILD_SHARED_LIBS=OFF

      - name: Build for iOS
        run: cmake --build build-ios --config Release

      - name: Package Unsigned IPA
        run: |
          APP_NAME=MyApp
          mkdir -p Payload
          cp -R build-ios/Release-iphoneos/${APP_NAME}.app Payload/
          zip -r ${APP_NAME}-unsigned.ipa Payload
          rm -rf Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: '*.ipa'
